/**
 * Master data for 25 Country Landing Pages
 * Based on SEO Blueprint — each country gets unique, market-specific content
 * to rank for "[Product] Supplier [Country]" keywords globally.
 */

export interface CountryData {
  slug: string;
  name: string;
  flag: string;
  region: string;
  currency: string;
  /** Primary B2B buyer segments in this country */
  buyerSegments: string[];
  /** Primary SEO keywords for this country */
  primaryKeywords: string[];
  /** Market-specific intro text */
  marketIntro: string;
  /** Why this country imports psyllium from India */
  importReason: string;
  /** Key certifications buyers in this country require */
  certifications: string[];
  /** Relevant port/logistics info */
  logistics: string;
  /** Country-specific FAQ */
  faqs: { q: string; a: string }[];
  /** Regulatory body or standard relevant to this market */
  regulatoryNote: string;
}

export const COUNTRIES: CountryData[] = [
  {
    slug: 'usa',
    name: 'United States',
    flag: '🇺🇸',
    region: 'North America',
    currency: 'USD',
    buyerSegments: ['Nutraceutical brands', 'Pharma manufacturers', 'Private label supplement companies', 'Health food retailers'],
    primaryKeywords: ['Psyllium Husk Supplier USA', 'Bulk Psyllium Husk USA', 'Organic Psyllium Husk Supplier USA', 'Isabgol Exporter USA', 'Psyllium Husk Importer USA'],
    marketIntro: 'The United States is the world\'s largest consumer market for psyllium husk, driven by a booming dietary fiber supplement industry valued at over $5 billion annually. US nutraceutical brands, private label manufacturers, and pharma companies consistently seek reliable, certified bulk psyllium husk suppliers from India.',
    importReason: 'India supplies over 85% of global psyllium husk (Isabgol), and US importers prefer Indian suppliers for their competitive pricing, consistent quality, and ability to meet FDA and USDA Organic certification requirements. Farm-to-port traceability and full COA documentation are standard.',
    certifications: ['FDA-registered facility', 'USDA Organic (for organic grade)', 'Non-GMO Verified', 'Halal & Kosher', 'ISO 22000'],
    logistics: 'FOB Mundra or Nhava Sheva port. Estimated transit time to US West Coast (Los Angeles): 18–22 days. US East Coast (New York): 22–28 days. Full container loads (FCL) and LCL consolidation available.',
    regulatoryNote: 'Psyllium husk imported into the USA must comply with FDA 21 CFR regulations. Bulk pharmaceutical-grade psyllium must meet USP monograph specifications.',
    faqs: [
      { q: 'Can you supply FDA-compliant psyllium husk to the USA?', a: 'Yes. Our facility is FDA-registered and our psyllium husk meets all requirements under 21 CFR. We provide full documentation including COA, MSDS, and facility registration certificates for US customs clearance.' },
      { q: 'Do you offer USDA Organic certified psyllium husk for US buyers?', a: 'Absolutely. We supply USDA NOP certified organic psyllium husk, processed in dedicated organic lines. Our organic products come with a valid organic certificate from an accredited third-party certifying agent.' },
      { q: 'What is the minimum order quantity for psyllium husk exports to the USA?', a: 'Our standard MOQ is 1 Metric Ton (MT), but we accommodate smaller trial orders of 500 kg for first-time buyers. For FCL orders (20ft container ≈ 18–20 MT), we offer preferential pricing.' },
      { q: 'What are your payment terms for US buyers?', a: 'We accept T/T (Wire Transfer), Letter of Credit (L/C), and for established buyers, Net 30 terms on confirmed orders. A 30% advance is standard for first orders.' },
    ],
  },
  {
    slug: 'germany',
    name: 'Germany',
    flag: '🇩🇪',
    region: 'Europe',
    currency: 'EUR',
    buyerSegments: ['Pharmaceutical companies', 'Health supplement manufacturers', 'Organic food brands', 'Natural remedy distributors'],
    primaryKeywords: ['Psyllium Husk Supplier Germany', 'Psyllium Lieferant Deutschland', 'Bulk Psyllium Husk Germany', 'Organic Psyllium Germany', 'Isabgol Exporter Germany'],
    marketIntro: 'Germany is Europe\'s largest pharmaceutical and natural health products market, with one of the highest per-capita consumptions of psyllium husk globally. German pharma and nutraceutical companies demand the highest quality standards, including EU organic certification and rigorous heavy metal testing.',
    importReason: 'German importers source psyllium husk primarily from India due to India\'s unrivalled production capacity, competitive FOB pricing, and ability to comply with EU food safety regulations including EFSA standards and EU Organic (EC 834/2007) certification requirements.',
    certifications: ['EU Organic Certified', 'ISO 22000', 'HACCP', 'Halal', 'Kosher', 'GMP compliant'],
    logistics: 'FOB Mundra to Hamburg (DEHAM): approximately 20–24 days. Rotterdam (NLRTM) as alternative EU gateway: 18–22 days. Full documentation: EUR 1, phytosanitary certificate, COA, packing list.',
    regulatoryNote: 'Imports into Germany (EU) are regulated under EU Novel Food Regulation (EU) 2015/2283 and EU Organic Regulation (EU) 2018/848. Psyllium husk is classified as a functional food ingredient.',
    faqs: [
      { q: 'Is your psyllium husk compliant with EU organic regulations?', a: 'Yes. We hold EU Organic certification (EU) 2018/848. Our organic psyllium husk can be sold as organic in all EU member states, including Germany, with our certificate as documentation.' },
      { q: 'Do you provide EUR 1 movement certificates for German customs?', a: 'Yes. We provide all required EU import documentation including EUR 1 movement certificates, phytosanitary certificates, COA, and MSDS sheets for smooth German customs clearance.' },
      { q: 'What heavy metal testing do you conduct for EU buyers?', a: 'Every batch undergoes third-party testing for Lead, Cadmium, Mercury, and Arsenic per EU Regulation (EC) No 1881/2006 limits. Results are included in the COA provided with each shipment.' },
      { q: 'Can you supply private label psyllium husk for German supplement brands?', a: 'Yes. We offer complete private label services including custom packaging, German-language label design support, and product formulation consulting. MOQ for private label: 500 kg.' },
    ],
  },
  {
    slug: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    region: 'Europe',
    currency: 'GBP',
    buyerSegments: ['Holland & Barrett type retailers', 'Supplement brands', 'Pharma companies', 'Online health retailers'],
    primaryKeywords: ['Psyllium Husk Supplier UK', 'Bulk Psyllium Husk UK', 'Organic Psyllium Husk UK', 'Isabgol Supplier United Kingdom', 'Psyllium Husk Importer UK'],
    marketIntro: 'The UK is one of the world\'s most sophisticated dietary supplement markets, with psyllium husk featuring prominently as a soluble fibre supplement, IBS management product, and cholesterol-lowering ingredient. UK buyers range from major health retailers to fast-growing direct-to-consumer supplement brands.',
    importReason: 'Post-Brexit, UK importers maintain direct relationships with Indian psyllium suppliers to ensure supply chain continuity. India remains the primary origin for bulk psyllium husk due to superior quality consistency and competitive pricing versus other producing countries.',
    certifications: ['UKCA compliant', 'EU Organic (still accepted in UK)', 'ISO 22000', 'Halal', 'Kosher', 'FSSAI'],
    logistics: 'FOB Mundra/Nhava Sheva to Felixstowe (UK\'s busiest container port): 22–26 days. Southampton alternative: similar transit. Full UK import documentation provided.',
    regulatoryNote: 'Post-Brexit UK food supplement regulations are governed by the FSA (Food Standards Agency) and follow retained EU law. Psyllium husk health claims are permitted under UK retained Regulation (EU) No 432/2012.',
    faqs: [
      { q: 'Is your psyllium husk suitable for UK food supplement regulations post-Brexit?', a: 'Yes. Our psyllium husk meets all UK FSA requirements. We provide full COA with nutritional analysis and are familiar with UK import documentation requirements including port health authority clearance.' },
      { q: 'Can psyllium husk make health claims in the UK market?', a: 'Yes. Psyllium husk has approved health claims in the UK under retained EU Regulation 432/2012 — specifically for maintaining normal bowel function and reducing blood cholesterol levels.' },
      { q: 'What packaging formats are available for UK buyers?', a: 'We offer 25 kg PP woven bags, 50 kg bags, HDPE drums, and custom consumer packaging down to 200g pouches for private label. Food-grade and pharmaceutical-grade packaging options available.' },
      { q: 'Do you have UK buyers we can reference?', a: 'We have established relationships with UK importers and distributors, though we maintain confidentiality per our agreements. We can provide trade references upon request during the qualification process.' },
    ],
  },
  {
    slug: 'canada',
    name: 'Canada',
    flag: '🇨🇦',
    region: 'North America',
    currency: 'CAD',
    buyerSegments: ['NPN licensed supplement brands', 'Pharma companies', 'Organic food manufacturers', 'Health food distributors'],
    primaryKeywords: ['Psyllium Husk Supplier Canada', 'Bulk Psyllium Husk Canada', 'Organic Psyllium Canada', 'Isabgol Supplier Canada', 'Psyllium Husk Importer Canada'],
    marketIntro: 'Canada\'s natural health product industry is one of the most regulated and respected globally. Psyllium husk is classified as a Natural Health Product (NHP) in Canada, requiring NPN (Natural Product Number) licensing. Canadian buyers seek suppliers who can provide rigorous documentation to support NPN applications.',
    importReason: 'Canadian NHP brands import bulk psyllium husk from India to formulate fibre supplements, laxatives, and functional foods. India\'s certified organic psyllium is especially sought after by Canada\'s growing organic supplement sector.',
    certifications: ['Health Canada NHP documentation ready', 'USDA/CFIA recognized organic', 'ISO 22000', 'Non-GMO', 'Kosher', 'Halal'],
    logistics: 'FOB Mundra to Vancouver: 18–22 days. Toronto via Halifax: 24–28 days. CFIA import permit documentation provided.',
    regulatoryNote: 'In Canada, psyllium husk is regulated under the Natural Health Products Regulations (NHPR) by Health Canada. Suppliers must provide evidence of quality, purity, and potency for NPN applications.',
    faqs: [
      { q: 'Can you provide documentation to support a Health Canada NPN application?', a: 'Yes. We provide comprehensive technical documentation including: product specifications, COA with quantitative analysis, manufacturing process description, stability data, and quality assurance documentation to support NPN submissions.' },
      { q: 'Is your psyllium husk Non-GMO verified for Canadian organic brands?', a: 'Yes. Psyllium (Plantago ovata) is inherently non-GMO. We provide Non-GMO declaration letters and our organic grade comes with USDA/EU organic certification accepted by CFIA.' },
      { q: 'What is the lead time for shipments to Canada?', a: 'Standard lead time is 7–14 days post order confirmation for production and quality testing. Transit time to Canadian ports is 18–28 days depending on destination port.' },
      { q: 'Do you offer custom private label services for Canadian brands?', a: 'Yes, including bilingual English/French label design support as required by Canadian labelling regulations. MOQ for private label starts at 500 kg.' },
    ],
  },
  {
    slug: 'australia',
    name: 'Australia',
    flag: '🇦🇺',
    region: 'Asia-Pacific',
    currency: 'AUD',
    buyerSegments: ['TGA licensed manufacturers', 'Organic supplement brands', 'Health food distributors', 'Pharmacy chains'],
    primaryKeywords: ['Psyllium Husk Supplier Australia', 'Bulk Psyllium Husk Australia', 'Organic Psyllium Australia', 'Isabgol Exporter Australia', 'Psyllium Husk Importer Australia'],
    marketIntro: 'Australia\'s complementary medicine market is one of the fastest growing in the Asia-Pacific region, valued at over AUD 5.6 billion. Psyllium husk is a TGA-listed complementary medicine ingredient, widely used in IBS treatments, cholesterol management supplements, and high-fiber functional foods.',
    importReason: 'Australian manufacturers import bulk psyllium husk from India due to price advantages, superior product quality, and India\'s ability to supply both conventional and USDA/ACO-certified organic grades. Direct sourcing from Amar Herbal Origins eliminates intermediary markups.',
    certifications: ['TGA-listed ingredient documentation', 'ACO Organic (Australian Certified Organic)', 'ISO 22000', 'HACCP', 'Halal', 'Kosher'],
    logistics: 'FOB Mundra to Melbourne: 14–18 days. Sydney: 15–19 days. AQIS biosecurity import documentation provided for smooth Australian border clearance.',
    regulatoryNote: 'In Australia, psyllium husk listed in complementary medicines is regulated by the TGA (Therapeutic Goods Administration). Bulk active ingredient suppliers must comply with TGA ARTG listing requirements.',
    faqs: [
      { q: 'Is your psyllium husk suitable for TGA-listed complementary medicines?', a: 'Yes. We supply pharmaceutical-grade psyllium husk that meets TGA requirements including BP (British Pharmacopoeia) and USP monograph standards. Full technical dossier available for TGA submissions.' },
      { q: 'Do you hold ACO (Australian Certified Organic) recognition?', a: 'Our organic psyllium carries USDA NOP and EU Organic certification, both of which are recognized by ACO under equivalency arrangements. We can provide additional ACO-specific documentation upon request.' },
      { q: 'What AQIS documentation do you provide for Australian import clearance?', a: 'We provide phytosanitary certificates issued by Indian plant quarantine authorities, COA, country of origin certificates, and commercial invoice — all required for Australian biosecurity clearance.' },
      { q: 'What are shipping costs from India to Australia?', a: 'FOB pricing is provided from Mundra or Nhava Sheva port. Freight costs to Australia depend on volume and current market rates. We assist in connecting you with competitive freight forwarders for CIF pricing.' },
    ],
  },
  {
    slug: 'uae',
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    region: 'Middle East',
    currency: 'AED',
    buyerSegments: ['Food & beverage manufacturers', 'Pharma distributors', 'Supplement companies', 'Re-export traders to GCC'],
    primaryKeywords: ['Psyllium Husk Supplier UAE', 'Bulk Psyllium Husk Dubai', 'Isabgol Supplier UAE', 'Psyllium Husk Exporter UAE', 'Organic Psyllium UAE'],
    marketIntro: 'The UAE — particularly Dubai — serves as the gateway for psyllium husk distribution across the GCC region, MENA markets, and beyond. UAE-based food manufacturers, pharma distributors, and re-export traders are among the most active buyers of bulk Indian psyllium husk globally.',
    importReason: 'India\'s proximity to UAE (shortest sea freight route), zero-duty import under India-UAE CEPA (Comprehensive Economic Partnership Agreement), and established trade relationships make Indian psyllium suppliers the preferred choice for UAE buyers.',
    certifications: ['Halal certified (mandatory)', 'ISO 22000', 'ESMA compliant', 'HACCP', 'Country of Origin Certificate'],
    logistics: 'FOB Mundra to Jebel Ali (Dubai): 7–10 days. One of the fastest and cheapest sea freight routes for Indian exporters. Documentation: Halal certificate, COO, COA, commercial invoice, packing list.',
    regulatoryNote: 'All food imports into UAE must comply with ESMA (Emirates Authority for Standardization and Metrology) standards. Halal certification is mandatory for food-grade psyllium husk products entering UAE.',
    faqs: [
      { q: 'Is your psyllium husk Halal certified for UAE import?', a: 'Yes. All our psyllium husk products carry Halal certification from an ESMA-recognized certifying body. Halal certificates are provided with every shipment for UAE customs clearance.' },
      { q: 'How quickly can you ship to Dubai/Jebel Ali?', a: 'Jebel Ali is our fastest export destination — FOB Mundra to Jebel Ali is just 7–10 days sea freight. With production lead time of 7–10 days, you can receive your order in approximately 3 weeks.' },
      { q: 'Can UAE buyers use your products for GCC re-export?', a: 'Absolutely. We provide all documentation required for UAE free zone operations and GCC re-export, including COO certificates, multi-country quality documentation, and flexible packaging options.' },
      { q: 'Do you offer Arabic-language packaging for UAE retail distribution?', a: 'Yes. For private label orders, we can design Arabic/English bilingual packaging compliant with UAE food labeling regulations (GSO 9/2013).' },
    ],
  },
  {
    slug: 'saudi-arabia',
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    region: 'Middle East',
    currency: 'SAR',
    buyerSegments: ['SFDA-registered distributors', 'Pharma companies', 'Food manufacturers', 'Health supplement brands'],
    primaryKeywords: ['Psyllium Husk Supplier Saudi Arabia', 'Isabgol Supplier KSA', 'Bulk Psyllium Saudi Arabia', 'Organic Psyllium Saudi Arabia', 'Psyllium Husk Exporter KSA'],
    marketIntro: 'Saudi Arabia is the largest economy in the Arab world and one of the fastest-growing markets for health supplements and functional foods in the MENA region. The SFDA (Saudi Food and Drug Authority) regulates all food supplement imports, and psyllium husk is a popular ingredient in digestive health and weight management products.',
    importReason: 'Saudi manufacturers and distributors import bulk psyllium husk from India as it is the world\'s dominant producer. Indian suppliers offer Halal-certified products with full SFDA-compatible documentation at competitive prices.',
    certifications: ['Halal certified (SFDA required)', 'ISO 22000', 'SASO compliant', 'COO from FIEO/APEDA', 'HACCP'],
    logistics: 'FOB Mundra to Jeddah Islamic Port or Dammam: 10–14 days. Documentation: SASO Certificate of Conformity, Halal certificate, phytosanitary certificate, COA.',
    regulatoryNote: 'Imports into Saudi Arabia must comply with SFDA requirements and SASO (Saudi Standards, Metrology and Quality Organization) standards. Pre-shipment certificate of conformity from accredited body required.',
    faqs: [
      { q: 'Do you provide SFDA-compliant documentation for Saudi Arabia imports?', a: 'Yes. We supply all documentation required for Saudi imports including: Halal certificate, COA, SASO certificate of conformity, phytosanitary certificate, and Arabic product description where needed.' },
      { q: 'Is your psyllium husk certified Halal per Saudi/GCC standards?', a: 'Yes. Our Halal certification is from a body recognized by the Saudi Halal Center. All production follows Halal manufacturing protocols with segregated processing lines.' },
      { q: 'What is the transit time from India to Saudi Arabia?', a: 'Sea freight from Mundra to Jeddah or Dammam takes approximately 10–14 days. With production lead time, expect total delivery in 3–4 weeks from order confirmation.' },
      { q: 'Can you supply psyllium husk for SFDA registered dietary supplement products?', a: 'Yes. We provide full ingredient documentation packages for SFDA supplement product registration, including specification sheets, COA, stability data, and manufacturing compliance certificates.' },
    ],
  },
  {
    slug: 'netherlands',
    name: 'Netherlands',
    flag: '🇳🇱',
    region: 'Europe',
    currency: 'EUR',
    buyerSegments: ['EU distribution hubs', 'Health food importers', 'Pharmaceutical ingredient distributors', 'Organic product re-exporters'],
    primaryKeywords: ['Psyllium Husk Supplier Netherlands', 'Bulk Psyllium Husk Holland', 'Organic Psyllium Netherlands', 'Psyllium Husk Importer Rotterdam', 'Isabgol Supplier Netherlands'],
    marketIntro: 'The Netherlands — particularly Rotterdam — is the largest port in Europe and the primary entry point for Indian agricultural commodities into the EU. Dutch distributors and ingredient suppliers serve as intermediaries for the entire European market, making the Netherlands a strategic hub for psyllium husk imports.',
    importReason: 'Rotterdam\'s position as Europe\'s largest port, combined with the Netherlands\' robust customs infrastructure and distribution networks, makes Dutch importers the preferred European buyers for bulk Indian psyllium husk intended for EU-wide distribution.',
    certifications: ['EU Organic Certified', 'ISO 22000', 'HACCP', 'EU food safety documentation', 'EUR 1 movement certificate'],
    logistics: 'FOB Mundra to Rotterdam (NLRTM): 18–22 days — one of the most well-established India-Europe freight routes with multiple weekly sailings.',
    regulatoryNote: 'All food imports into the Netherlands follow EU regulations. Dutch customs (Douane) applies EU food safety standards including EFSA guidance and Regulation (EC) 178/2002.',
    faqs: [
      { q: 'Can you supply psyllium husk for EU-wide distribution via Rotterdam?', a: 'Yes. We are experienced with Rotterdam-destined shipments. We provide EUR 1 movement certificates and all EU import documentation required for Dutch customs clearance and onward EU distribution.' },
      { q: 'What EU food safety certificates accompany your products?', a: 'We provide: COA with heavy metals, pesticide residues, microbiology testing per EU limits; phytosanitary certificate; EUR 1; and EU Organic certificate for organic grade products.' },
      { q: 'Do you work with Dutch trading companies for EU re-distribution?', a: 'Yes. We supply to Dutch ingredient traders, distributors, and importers who then service customers across Germany, France, Belgium, Scandinavia, and other EU markets.' },
      { q: 'What are your FCL pricing terms for Rotterdam?', a: 'We offer competitive FOB Mundra pricing for FCL shipments. CIF Rotterdam pricing is also available. Freight cost is competitive given the high volume of India-Rotterdam trade lanes.' },
    ],
  },
  {
    slug: 'france',
    name: 'France',
    flag: '🇫🇷',
    region: 'Europe',
    currency: 'EUR',
    buyerSegments: ['Pharma ingredient companies', 'Organic supplement brands', 'Parapharmacy chains', 'Natural health distributors'],
    primaryKeywords: ['Psyllium Husk Supplier France', 'Fournisseur Psyllium France', 'Organic Psyllium France', 'Bulk Psyllium Husk France', 'Isabgol Supplier France'],
    marketIntro: 'France is Europe\'s second-largest pharmaceutical market and has a strong parapharmacy (parapharmacie) sector where psyllium husk products are widely sold for digestive health. French consumers are health-conscious, and demand for organic and clean-label ingredients is growing rapidly.',
    importReason: 'French pharma and supplement manufacturers import pharmaceutical-grade psyllium husk from India for formulating laxative preparations (Psyllium is classified as a laxative in French pharmacopoeia), dietary supplements, and high-fibre food products.',
    certifications: ['EU Organic Certified', 'European Pharmacopoeia (Ph. Eur.) compliant', 'ISO 22000', 'HACCP', 'Halal', 'Kosher'],
    logistics: 'FOB Mundra to Le Havre (FRLEH) or Marseille (FRMRS): 20–24 days.',
    regulatoryNote: 'In France, psyllium is classified as both a food ingredient and a pharmaceutical active ingredient. Pharma-grade supply must comply with European Pharmacopoeia (Ph. Eur.) monograph for Ispaghula Husk.',
    faqs: [
      { q: 'Does your psyllium husk meet European Pharmacopoeia (Ph. Eur.) standards?', a: 'Yes. We supply pharmaceutical-grade psyllium husk that meets the Ph. Eur. monograph for Ispaghula Husk, including swelling index requirements (≥ 40 ml/g) and purity specifications.' },
      { q: 'Can you supply psyllium for French parapharmacy products?', a: 'Absolutely. We regularly supply to pharma-grade applications including OTC laxative preparations common in French parapharmacies. All COA and technical documentation provided.' },
      { q: 'Do you have EU Organic certification for France?', a: 'Yes. Our organic psyllium is certified under EU Organic Regulation (EU) 2018/848, valid across all EU member states including France.' },
      { q: 'Can you provide French-language documentation?', a: 'We can provide technical documentation in English, and assist with document translation requirements. Our French buyer support ensures smooth import clearance.' },
    ],
  },
  {
    slug: 'japan',
    name: 'Japan',
    flag: '🇯🇵',
    region: 'Asia-Pacific',
    currency: 'JPY',
    buyerSegments: ['Functional food manufacturers', 'Health supplement companies', 'FOSHU product developers', 'Trading companies (Sogoshosha)'],
    primaryKeywords: ['Psyllium Husk Supplier Japan', 'Psyllium Husk Japan Import', 'Bulk Psyllium Japan', 'Organic Psyllium Japan', 'Isabgol Exporter Japan'],
    marketIntro: 'Japan\'s functional food and health supplement market is one of the most innovative in the world, with a unique regulatory framework for Foods for Specified Health Uses (FOSHU — 特定保健用食品). Psyllium husk holds an approved FOSHU claim in Japan for maintaining normal cholesterol levels, making it a premium ingredient for Japanese food companies.',
    importReason: 'Japan imports psyllium husk from India due to quality consistency, competitive pricing, and India\'s ability to supply to Japanese-standard specifications. Japanese trading houses (Sogoshosha) and direct ingredient importers are the primary buyers.',
    certifications: ['JAS Organic (for organic grade)', 'ISO 22000', 'Halal', 'Kosher', 'MHLW Food Sanitation Act compliant'],
    logistics: 'FOB Mundra to Yokohama or Osaka: 15–20 days. Japanese import documentation including Customs Form C-5360 and quarantine inspection support provided.',
    regulatoryNote: 'Imports are regulated under Japan\'s Food Sanitation Act (食品衛生法) by MHLW. Pesticide residue limits are strict under Japan\'s Positive List System. Japanese buyers require detailed pesticide testing reports.',
    faqs: [
      { q: 'Does your psyllium husk comply with Japan\'s Positive List System for pesticide residues?', a: 'Yes. We conduct comprehensive pesticide residue testing per Japan\'s Positive List System requirements. Testing is performed by accredited third-party laboratories and results are included in the COA.' },
      { q: 'Can your psyllium husk be used in FOSHU (Foods for Specified Health Uses) products?', a: 'Our pharmaceutical-grade psyllium husk meets the quality specifications required for FOSHU applications. The approved FOSHU claim for psyllium in Japan covers cholesterol management — we supply to manufacturers with active FOSHU approvals.' },
      { q: 'Do you work with Japanese Sogoshosha (trading companies)?', a: 'Yes. We have experience working with Japanese trading houses. We accommodate Japanese documentation standards, quality inspection requirements, and provide samples for internal testing.' },
      { q: 'What are Japanese customs tariff rates for psyllium husk imports from India?', a: 'Under the India-Japan CEPA (Comprehensive Economic Partnership Agreement), psyllium husk (HS code 1211.90) enjoys preferential tariff rates. Your customs broker can provide exact current rates.' },
    ],
  },
  {
    slug: 'south-korea',
    name: 'South Korea',
    flag: '🇰🇷',
    region: 'Asia-Pacific',
    currency: 'KRW',
    buyerSegments: ['Health functional food manufacturers', 'Pharma companies', 'K-beauty ingredient suppliers', 'Online supplement retailers'],
    primaryKeywords: ['Psyllium Husk Supplier South Korea', 'Bulk Psyllium Korea', 'Organic Psyllium South Korea', 'Isabgol Exporter Korea', 'Psyllium Husk Import Korea'],
    marketIntro: 'South Korea has one of the world\'s most sophisticated health functional food (HFF) markets. The MFDS (Ministry of Food and Drug Safety) regulates health functional food ingredients, and psyllium husk is approved as a functional ingredient for intestinal health and cholesterol management.',
    importReason: 'Korean HFF manufacturers and pharma companies import high-purity psyllium husk from India for supplement capsules, powder sachets, and functional beverages. India\'s competitive pricing and quality consistency are key advantages.',
    certifications: ['MFDS functional food ingredient documentation', 'ISO 22000', 'Halal', 'HACCP', 'Kosher'],
    logistics: 'FOB Mundra to Busan (KRPUS): 12–16 days. Korea-India trade lane is well-established with multiple weekly sailings.',
    regulatoryNote: 'South Korea regulates health functional food ingredients under the Health Functional Food Act. Psyllium husk must meet MFDS standards for HFF ingredient quality.',
    faqs: [
      { q: 'Is your psyllium husk approved for Korean Health Functional Food (HFF) products?', a: 'Yes. Psyllium husk is listed as an approved functional food ingredient by MFDS Korea. We provide the full ingredient technical documentation package required for HFF product approval applications.' },
      { q: 'What is the transit time from India to South Korea?', a: 'Sea freight from Mundra to Busan takes 12–16 days. We have regular shipments to Korea and can coordinate with Korean freight forwarders.' },
      { q: 'Do you supply psyllium to Korean pharma and supplement OEM manufacturers?', a: 'Yes. We supply to Korean OEM manufacturers producing psyllium supplements in capsule, tablet, powder sachet, and stick pack formats. Custom specifications available.' },
      { q: 'Can you provide Korean-language product specifications?', a: 'We can provide technical specifications in English and assist with translation requirements. We work with Korean importers who handle customs clearance and Korean regulatory requirements.' },
    ],
  },
  {
    slug: 'singapore',
    name: 'Singapore',
    flag: '🇸🇬',
    region: 'Asia-Pacific',
    currency: 'SGD',
    buyerSegments: ['HSA-licensed manufacturers', 'Regional distribution hubs', 'Health supplement brands', 'ASEAN re-exporters'],
    primaryKeywords: ['Psyllium Husk Supplier Singapore', 'Bulk Psyllium Singapore', 'Organic Psyllium Singapore', 'Isabgol Supplier Singapore', 'Psyllium Husk Importer Singapore'],
    marketIntro: 'Singapore functions as the primary health supplement trade hub for the ASEAN region. HSA (Health Sciences Authority) regulates health product imports, and Singapore-based companies often source and re-distribute to Malaysia, Indonesia, Thailand, Vietnam, and other ASEAN markets.',
    importReason: 'Singapore\'s strategic location, world-class port infrastructure, and excellent cold chain and warehousing facilities make it an ideal regional distribution center. Indian psyllium suppliers can serve the entire ASEAN market via Singapore-based partners.',
    certifications: ['HSA compliant documentation', 'ISO 22000', 'Halal (MUIS certified)', 'Kosher', 'Non-GMO'],
    logistics: 'FOB Mundra to Singapore (SGSIN): 10–14 days. One of the fastest India-ASEAN freight routes.',
    regulatoryNote: 'Psyllium husk health products in Singapore are regulated under HSA\'s Health Products Act. MUIS Halal certification is important for Muslim-majority ASEAN market distribution.',
    faqs: [
      { q: 'Can Singapore distributors use your psyllium for ASEAN-wide distribution?', a: 'Yes. We supply to Singapore-based ingredient distributors and traders who serve Malaysia, Indonesia, Thailand, Philippines, and Vietnam. We provide documentation suitable for ASEAN market requirements.' },
      { q: 'Is your psyllium MUIS Halal certified for Singapore and Malaysia distribution?', a: 'Yes. Our Halal certificate is from a body recognized by MUIS (Majlis Ugama Islam Singapura), enabling distribution across Singapore and Muslim-majority ASEAN markets.' },
      { q: 'What is the minimum order for Singapore buyers?', a: 'MOQ is 1 MT for standard grades. For Singapore-based distributors managing ASEAN distribution, we offer flexible LCL shipments for trial orders and FCL for regular orders.' },
      { q: 'Do you have experience with Singapore port clearance?', a: 'Yes. We have multiple Singapore-destined shipments and work with experienced freight forwarders familiar with Singapore customs (Singapore Customs) and SFA (Singapore Food Agency) import requirements.' },
    ],
  },
  {
    slug: 'malaysia',
    name: 'Malaysia',
    flag: '🇲🇾',
    region: 'Asia-Pacific',
    currency: 'MYR',
    buyerSegments: ['NPRA-registered manufacturers', 'Halal food companies', 'Health supplement brands', 'Pharmacy chains'],
    primaryKeywords: ['Psyllium Husk Supplier Malaysia', 'Bulk Psyllium Malaysia', 'Organic Psyllium Malaysia', 'Isabgol Supplier Malaysia', 'Halal Psyllium Malaysia'],
    marketIntro: 'Malaysia is a key psyllium husk market in ASEAN, with strong demand from both the Halal food industry and growing health supplement sector. NPRA (National Pharmaceutical Regulatory Agency) regulates health supplement products, and Halal certification is essential.',
    importReason: 'Malaysian manufacturers import psyllium husk from India for Halal-certified digestive health supplements, functional foods, and OTC laxative preparations. India\'s competitive pricing and Halal certification capabilities make it the preferred source.',
    certifications: ['JAKIM Halal certified (essential)', 'MeSTI compliant', 'ISO 22000', 'HACCP', 'Kosher'],
    logistics: 'FOB Mundra to Port Klang (Klang, near Kuala Lumpur): 12–16 days. Well-established India-Malaysia trade lane.',
    regulatoryNote: 'Health supplements in Malaysia are regulated by NPRA under the Control of Drugs and Cosmetics Regulations 1984. Halal certification from JAKIM is essential for Muslim-market products.',
    faqs: [
      { q: 'Is your psyllium husk JAKIM Halal certified for Malaysia?', a: 'Our Halal certification covers our production facility and processes. For JAKIM-specific requirements, we work with our buyers to provide the necessary documentation for Malaysian Halal product registration.' },
      { q: 'Can you supply psyllium for NPRA product registration in Malaysia?', a: 'Yes. We provide complete technical dossiers required for NPRA registration including specifications, COA, manufacturing process descriptions, and stability data.' },
      { q: 'What is the sea freight time from India to Malaysia?', a: 'FOB Mundra to Port Klang takes 12–16 days. Combined with our 7–10 day production lead time, total delivery is approximately 3 weeks.' },
      { q: 'Do you offer MeSTI-compatible documentation for Malaysian food manufacturers?', a: 'Yes. We provide all documentation required for MeSTI (Ministry of Domestic Trade) food safety scheme compliance.' },
    ],
  },
  {
    slug: 'italy',
    name: 'Italy',
    flag: '🇮🇹',
    region: 'Europe',
    currency: 'EUR',
    buyerSegments: ['Nutraceutical companies', 'Pharma manufacturers', 'Herbal supplement brands', 'Functional food producers'],
    primaryKeywords: ['Psyllium Husk Supplier Italy', 'Fornitore Psillio Italia', 'Bulk Psyllium Italy', 'Organic Psyllium Italy', 'Isabgol Supplier Italy'],
    marketIntro: 'Italy is Europe\'s largest nutraceutical market, with psyllium husk widely used in dietary supplements, herbal laxative preparations, and functional foods. Italian nutraceutical companies ("integratori alimentari") have a strong tradition of using plant-based ingredients like psyllium.',
    importReason: 'Italian nutraceutical and pharma companies import pharmaceutical-grade psyllium husk from India for formulating fiber supplements and laxative products sold across Europe. The Italian market values quality, certification, and competitive pricing.',
    certifications: ['EU Organic Certified', 'European Pharmacopoeia compliant', 'ISO 22000', 'HACCP', 'Halal', 'Kosher'],
    logistics: 'FOB Mundra to Genoa (ITGOA) or La Spezia: 20–25 days. Trieste also used for Northern Italy.',
    regulatoryNote: 'Italian food supplements are regulated by the Ministero della Salute under EU Directive 2002/46/EC. Psyllium husk in supplements is classified under "fibra alimentare."',
    faqs: [
      { q: 'Does your psyllium husk meet Italian/EU nutraceutical standards?', a: 'Yes. Our psyllium meets all EU food supplement standards and European Pharmacopoeia specifications. Full Italian/EU-compliant documentation provided with every shipment.' },
      { q: 'Can you supply pharma-grade psyllium for Italian OTC laxative products?', a: 'Yes. We supply Ph. Eur. grade psyllium husk used in OTC laxative preparations. Documentation supports Italian pharmaceutical registration requirements.' },
      { q: 'What is transit time from India to Italy?', a: 'FOB Mundra to Genoa or La Spezia takes 20–25 days via major shipping lines.' },
      { q: 'Do you have experience with Italian pharma and nutraceutical companies?', a: 'Yes. We supply to European buyers including Italian nutraceutical manufacturers. We understand Italian regulatory requirements and provide appropriate technical documentation.' },
    ],
  },
  {
    slug: 'spain',
    name: 'Spain',
    flag: '🇪🇸',
    region: 'Europe',
    currency: 'EUR',
    buyerSegments: ['Farmacéutica companies', 'Supplement manufacturers', 'Organic food brands', 'Health distributors'],
    primaryKeywords: ['Psyllium Husk Supplier Spain', 'Proveedor Psilio España', 'Bulk Psyllium Spain', 'Organic Psyllium Spain', 'Isabgol Supplier Spain'],
    marketIntro: 'Spain has a growing natural health and dietary supplement market, with psyllium husk ("cáscara de psilio") recognized by AEMPS as a traditional herbal remedy for constipation and cholesterol management. Spanish pharma and supplement companies increasingly source directly from Indian manufacturers.',
    importReason: 'Spanish manufacturers import bulk psyllium from India for pharmaceutical preparations (AEMPS registered), food supplements, and organic health products. India\'s EU Organic certified psyllium is particularly valued.',
    certifications: ['EU Organic Certified', 'AEMPS documentation compatible', 'ISO 22000', 'Halal', 'Kosher', 'European Pharmacopoeia compliant'],
    logistics: 'FOB Mundra to Barcelona (ESBCN) or Valencia (ESVLC): 20–24 days.',
    regulatoryNote: 'In Spain, psyllium husk products are regulated by AEMPS (Agencia Española de Medicamentos y Productos Sanitarios) for pharmaceutical applications and AESAN for food supplements.',
    faqs: [
      { q: 'Is your psyllium husk compatible with AEMPS requirements in Spain?', a: 'Yes. We provide full pharmaceutical technical documentation compatible with AEMPS requirements for traditional herbal medicinal products containing psyllium husk.' },
      { q: 'Do you have EU Organic certification for the Spanish market?', a: 'Yes. Our organic psyllium carries EU Organic certification valid across Spain and all EU markets.' },
      { q: 'What is the transit time from India to Spain?', a: 'Sea freight from Mundra to Barcelona or Valencia takes approximately 20–24 days.' },
      { q: 'Can you provide Spanish-language documentation support?', a: 'We provide technical documentation in English and can assist with Spanish translation requirements for regulatory submissions.' },
    ],
  },
  {
    slug: 'poland',
    name: 'Poland',
    flag: '🇵🇱',
    region: 'Europe',
    currency: 'PLN',
    buyerSegments: ['Supplement manufacturers', 'Health food distributors', 'Pharmacy networks', 'Private label brands'],
    primaryKeywords: ['Psyllium Husk Supplier Poland', 'Dostawca Babki Jajowatej Polska', 'Bulk Psyllium Poland', 'Organic Psyllium Poland', 'Isabgol Supplier Poland'],
    marketIntro: 'Poland is Central Europe\'s largest dietary supplement market with rapidly growing consumer health awareness. Polish supplement manufacturers ("suplementy diety") represent a major buyer segment for bulk psyllium husk, used in fiber supplements, laxatives, and cholesterol products.',
    importReason: 'Polish manufacturers import bulk psyllium from India as it is significantly more cost-competitive than EU-grown alternatives, while meeting all EU quality and organic certification requirements.',
    certifications: ['EU Organic Certified', 'ISO 22000', 'HACCP', 'Halal', 'Kosher'],
    logistics: 'FOB Mundra to Gdańsk (PLGDN) or Hamburg then road: 22–26 days.',
    regulatoryNote: 'Polish food supplements are regulated by GIS (Główny Inspektorat Sanitarny) and URPL for pharmaceutical products, all under EU framework regulations.',
    faqs: [
      { q: 'Is your psyllium husk compliant with Polish supplement regulations?', a: 'Yes. Polish supplements follow EU regulations (Directive 2002/46/EC) which our products fully comply with. We provide all EU-standard documentation.' },
      { q: 'Can you supply large volumes to Poland cost-effectively?', a: 'Poland is a price-sensitive market and we offer competitive bulk pricing. FCL shipments to Gdańsk or Hamburg (with road delivery to Poland) are cost-effective options.' },
      { q: 'What is transit time to Poland?', a: 'FOB Mundra to Gdańsk takes approximately 22–26 days. Alternatively, Hamburg gateway with road transport is also used by Polish importers.' },
      { q: 'Do you offer private label services for Polish supplement brands?', a: 'Yes. We offer private label psyllium husk products with Polish-language label compliance support. MOQ starts at 500 kg.' },
    ],
  },
  {
    slug: 'belgium',
    name: 'Belgium',
    flag: '🇧🇪',
    region: 'Europe',
    currency: 'EUR',
    buyerSegments: ['EU ingredient distributors', 'Pharma companies', 'Supplement manufacturers', 'Antwerp port traders'],
    primaryKeywords: ['Psyllium Husk Supplier Belgium', 'Bulk Psyllium Belgium', 'Organic Psyllium Belgium', 'Isabgol Supplier Belgium', 'Psyllium Husk Antwerp'],
    marketIntro: 'Belgium, home to the Port of Antwerp — Europe\'s second-largest port — is a key gateway for Indian agricultural commodities into Europe. Belgian distributors and traders supply psyllium husk to pharmaceutical and supplement companies across the Benelux region and wider EU.',
    importReason: 'Antwerp\'s deep-water port facilities and excellent European logistics connections make Belgium an important entry point for bulk psyllium husk from India. Belgian pharma and health ingredient companies are sophisticated buyers with high quality standards.',
    certifications: ['EU Organic Certified', 'ISO 22000', 'HACCP', 'Halal', 'Kosher', 'Belgian AFSCA compliant'],
    logistics: 'FOB Mundra to Antwerp (BEANR): 18–22 days. One of the most competitive India-Europe freight routes.',
    regulatoryNote: 'Imports are regulated by AFSCA (Federal Agency for the Safety of the Food Chain). All EU food safety regulations apply.',
    faqs: [
      { q: 'Do you ship to Antwerp for EU distribution?', a: 'Yes. Antwerp is one of our key European destination ports. We provide full EU import documentation for Belgian customs clearance via AFSCA.' },
      { q: 'What certifications do Belgian buyers require?', a: 'Belgian and EU buyers require EU Organic certification, ISO 22000, full COA with heavy metals and pesticide testing per EU limits, and AFSCA-compliant labeling and documentation.' },
      { q: 'Can you supply to Benelux distributors?', a: 'Yes. We work with distributors serving Belgium, Netherlands, and Luxembourg. Antwerp and Rotterdam are both natural distribution points for our European buyers.' },
      { q: 'What payment terms are available for Belgian buyers?', a: 'We offer T/T, L/C, and for established European distributors, Net 30 credit terms. Our standard terms for new buyers are 30% advance + 70% against shipping documents.' },
    ],
  },
  {
    slug: 'sweden',
    name: 'Sweden',
    flag: '🇸🇪',
    region: 'Europe',
    currency: 'SEK',
    buyerSegments: ['Nordic supplement brands', 'Organic product manufacturers', 'Pharmacy chains', 'Health food retailers'],
    primaryKeywords: ['Psyllium Husk Supplier Sweden', 'Bulk Psyllium Sverige', 'Organic Psyllium Sweden', 'Isabgol Supplier Sweden', 'Psyllium Husk Nordic'],
    marketIntro: 'Scandinavia, led by Sweden, has one of the highest per-capita health supplement spending rates in the world. Swedish consumers are particularly health-conscious and demand organic, sustainably sourced ingredients. Psyllium husk is a popular supplement ingredient in the Nordic market.',
    importReason: 'Swedish and Nordic supplement brands import certified organic psyllium husk from India for their premium product lines. Sweden\'s Livsmedelsverket (Swedish Food Agency) follows EU food safety standards, making Indian EU-certified psyllium fully compliant.',
    certifications: ['EU Organic Certified (KRAV recognized)', 'ISO 22000', 'Kosher', 'Halal', 'Non-GMO'],
    logistics: 'FOB Mundra to Gothenburg (SEGOT): 22–26 days. Gothenburg is Sweden\'s main container port.',
    regulatoryNote: 'Swedish food supplements are regulated by Livsmedelsverket under EU Directive 2002/46/EC. KRAV is Sweden\'s leading organic certification body; EU Organic is accepted.',
    faqs: [
      { q: 'Is your organic psyllium husk accepted for Swedish KRAV organic standards?', a: 'EU Organic certification (which we hold) is the basis for KRAV certification equivalency. Swedish organic brands typically accept EU Organic certified ingredients for their KRAV-labeled products.' },
      { q: 'What is the transit time from India to Sweden?', a: 'FOB Mundra to Gothenburg takes approximately 22–26 days via major shipping lines.' },
      { q: 'Do you supply to other Nordic countries too?', a: 'Yes. We supply psyllium husk to buyers across Sweden, Denmark, Norway, and Finland. Nordic supplement brands often buy collaboratively to consolidate container loads.' },
      { q: 'What sustainability documentation can you provide for Swedish brands?', a: 'We provide: farm-direct sourcing declaration, fair trade farming practice statements, organic certification, non-GMO declaration, and can arrange carbon footprint documentation for sustainability-focused buyers.' },
    ],
  },
  {
    slug: 'denmark',
    name: 'Denmark',
    flag: '🇩🇰',
    region: 'Europe',
    currency: 'DKK',
    buyerSegments: ['Nordic supplement brands', 'Pharma companies', 'Organic food manufacturers', 'Health retailers'],
    primaryKeywords: ['Psyllium Husk Supplier Denmark', 'Psyllium Leverandør Danmark', 'Bulk Psyllium Denmark', 'Organic Psyllium Denmark', 'Isabgol Supplier Denmark'],
    marketIntro: 'Denmark has a mature and highly regulated supplement and pharma market. Danish companies, including global pharmaceutical leaders, are discerning buyers who require stringent quality documentation. Psyllium husk is used in pharmaceutical laxatives and premium fiber supplements.',
    importReason: 'Danish pharma and nutraceutical companies import bulk psyllium from India for its quality, certification credentials, and competitive pricing. Danish buyers particularly value transparent supply chain documentation.',
    certifications: ['EU Organic Certified', 'European Pharmacopoeia compliant', 'ISO 22000', 'HACCP', 'Halal', 'Kosher'],
    logistics: 'FOB Mundra to Copenhagen (DKCPH) or Aarhus (DKAAR): 22–26 days.',
    regulatoryNote: 'Danish food supplements are regulated by the Danish Veterinary and Food Administration (Fødevarestyrelsen) under EU framework. Pharmaceutical products follow DKMA (Danish Medicines Agency) requirements.',
    faqs: [
      { q: 'Does your psyllium husk meet Danish pharma requirements?', a: 'Yes. We supply European Pharmacopoeia grade psyllium suitable for Danish pharmaceutical applications, with full technical documentation for DKMA submissions.' },
      { q: 'What EU import documentation do you provide for Denmark?', a: 'We provide: COA, EUR 1, phytosanitary certificate, EU Organic certificate, and customs-ready commercial documentation for Danish port clearance.' },
      { q: 'Can you supply trial quantities for product development?', a: 'Yes. We offer sample quantities of 1–5 kg for initial quality evaluation, and trial orders of 100–500 kg for production testing before full commercial orders.' },
      { q: 'What is your quality assurance process?', a: 'Every batch undergoes in-house QC testing followed by third-party accredited laboratory testing. We test for purity, moisture, swelling index, heavy metals, pesticide residues, and microbiological parameters.' },
    ],
  },
  {
    slug: 'new-zealand',
    name: 'New Zealand',
    flag: '🇳🇿',
    region: 'Asia-Pacific',
    currency: 'NZD',
    buyerSegments: ['Medsafe-registered manufacturers', 'Organic supplement brands', 'Health food companies', 'Pharmacy chains'],
    primaryKeywords: ['Psyllium Husk Supplier New Zealand', 'Bulk Psyllium New Zealand', 'Organic Psyllium NZ', 'Isabgol Supplier New Zealand', 'Psyllium Import New Zealand'],
    marketIntro: 'New Zealand\'s premium health and wellness market is closely aligned with Australian standards. NZ consumers have high demand for organic, traceable ingredients. Psyllium husk is sold across pharmacy chains, health food stores, and online supplement retailers.',
    importReason: 'NZ manufacturers import bulk psyllium husk from India as the primary global source. Indian suppliers can meet FSANZ (Food Standards Australia New Zealand) requirements and supply organic certified grades for NZ\'s growing premium health market.',
    certifications: ['FSANZ compliant', 'Medsafe documentation ready', 'USDA/ACO Organic recognized', 'Halal', 'Kosher'],
    logistics: 'FOB Mundra to Auckland (NZAKL): 18–22 days.',
    regulatoryNote: 'NZ food safety is governed by FSANZ under Australia New Zealand Food Standards Code. Therapeutic products follow Medsafe (NZ Medicines and Medical Devices Safety Authority) requirements.',
    faqs: [
      { q: 'Does your psyllium husk meet FSANZ (Australia New Zealand Food Standards) requirements?', a: 'Yes. Our psyllium meets FSANZ standards. We provide COA with FSANZ-aligned testing parameters and full food safety documentation.' },
      { q: 'What is transit time from India to New Zealand?', a: 'FOB Mundra to Auckland takes 18–22 days via major shipping services.' },
      { q: 'Can you supply small quantities for NZ boutique brands?', a: 'Yes. We accommodate smaller orders for boutique NZ health brands, including LCL shipments. MOQ starts at 500 kg for NZ buyers.' },
      { q: 'Do you provide organic psyllium suitable for NZ organic labeling?', a: 'Yes. Our USDA Organic and EU Organic certified psyllium is recognized in New Zealand. We provide certificates and origin documentation for NZ organic product claims.' },
    ],
  },
  {
    slug: 'south-africa',
    name: 'South Africa',
    flag: '🇿🇦',
    region: 'Africa',
    currency: 'ZAR',
    buyerSegments: ['SAHPRA registered companies', 'Supplement brands', 'Pharmacy distributors', 'Natural health product companies'],
    primaryKeywords: ['Psyllium Husk Supplier South Africa', 'Bulk Psyllium South Africa', 'Organic Psyllium South Africa', 'Isabgol Supplier South Africa', 'Psyllium Import South Africa'],
    marketIntro: 'South Africa is the gateway to Sub-Saharan Africa\'s growing health supplement market. SAHPRA (South African Health Products Regulatory Authority) regulates health products. Psyllium husk is widely used in SA\'s complement medicine sector and food industry.',
    importReason: 'South African importers source bulk psyllium husk from India due to competitive pricing, quality standards, and India\'s long-standing trade relationships with Southern Africa. The India-SA trade relationship benefits from favorable shipping routes via the Cape Town route.',
    certifications: ['SAHPRA documentation compatible', 'ISO 22000', 'Halal', 'Kosher', 'SABS compliant'],
    logistics: 'FOB Mundra to Durban (ZADDR) or Cape Town (ZACPT): 18–24 days.',
    regulatoryNote: 'Health supplements in SA are regulated by SAHPRA under the Medicines and Related Substances Act. Natural health products require SAHPRA notification or registration.',
    faqs: [
      { q: 'Is your psyllium compliant with SAHPRA requirements in South Africa?', a: 'Yes. We provide comprehensive technical documentation compatible with SAHPRA notification and registration requirements for complementary and health products.' },
      { q: 'What is the transit time to South Africa?', a: 'FOB Mundra to Durban takes approximately 18–24 days. Cape Town is a similar transit time.' },
      { q: 'Do you offer Halal certified psyllium for South African Muslim market?', a: 'Yes. Our Halal certification is provided with all shipments, important for South Africa\'s significant Muslim consumer market.' },
      { q: 'Can you supply psyllium for sub-Saharan Africa distribution from South Africa?', a: 'Yes. South African importers often use our products for regional distribution across SADC (Southern African Development Community) countries. We provide flexible packaging and documentation for regional distribution.' },
    ],
  },
  {
    slug: 'thailand',
    name: 'Thailand',
    flag: '🇹🇭',
    region: 'Asia-Pacific',
    currency: 'THB',
    buyerSegments: ['FDA Thailand licensed manufacturers', 'Herbal supplement companies', 'OTOP natural product brands', 'Health food distributors'],
    primaryKeywords: ['Psyllium Husk Supplier Thailand', 'Bulk Psyllium Thailand', 'Organic Psyllium Thailand', 'Isabgol Supplier Thailand', 'Psyllium Husk Bangkok'],
    marketIntro: 'Thailand is a major health supplement manufacturing hub in ASEAN, with strong government support for herbal and natural health products. Thai FDA regulates health product imports and the market for digestive health supplements is rapidly growing.',
    importReason: 'Thai supplement manufacturers import bulk psyllium husk from India for fiber supplement capsules, functional beverages, and natural laxative preparations. India\'s competitive pricing and halal certification are key advantages.',
    certifications: ['Thai FDA documentation compatible', 'Halal (CICOT recognized)', 'ISO 22000', 'HACCP', 'GMP compliant'],
    logistics: 'FOB Mundra to Laem Chabang (near Bangkok): 12–16 days.',
    regulatoryNote: 'Health products in Thailand are regulated by the Thai FDA under the Food Act B.E. 2522. Dietary fiber supplements require Thai FDA notification.',
    faqs: [
      { q: 'Is your psyllium compliant with Thai FDA requirements?', a: 'Yes. We provide technical documentation compatible with Thai FDA requirements for dietary supplement product registration and notification.' },
      { q: 'Do you supply Halal certified psyllium for Thai Muslim market?', a: 'Yes. Our Halal certification is recognized by CICOT (Central Islamic Council of Thailand), essential for Thailand\'s Muslim-majority southern provinces and ASEAN Halal market.' },
      { q: 'What is transit time from India to Thailand?', a: 'FOB Mundra to Laem Chabang (Bangkok) takes 12–16 days. One of the shorter India-ASEAN routes.' },
      { q: 'Can you supply psyllium for Thai herbal supplement manufacturers?', a: 'Yes. Thai herbal supplement companies are a key buyer segment. We supply pharma-grade psyllium for capsule, tablet, and powder sachet applications.' },
    ],
  },
  {
    slug: 'vietnam',
    name: 'Vietnam',
    flag: '🇻🇳',
    region: 'Asia-Pacific',
    currency: 'VND',
    buyerSegments: ['DAV licensed manufacturers', 'Health food companies', 'Supplement distributors', 'Traditional medicine companies'],
    primaryKeywords: ['Psyllium Husk Supplier Vietnam', 'Bulk Psyllium Vietnam', 'Organic Psyllium Vietnam', 'Isabgol Supplier Vietnam', 'Psyllium Ho Chi Minh'],
    marketIntro: 'Vietnam\'s health supplement and functional food market is one of the fastest growing in Southeast Asia, driven by rising middle-class health consciousness. The DAV (Drug Administration of Vietnam) regulates health supplement imports.',
    importReason: 'Vietnamese manufacturers import bulk psyllium husk from India for fiber supplement products — a fast-growing category in Vietnam\'s health product sector. India\'s competitive pricing and reliable supply are key purchase drivers.',
    certifications: ['DAV compliant documentation', 'ISO 22000', 'Halal', 'HACCP', 'GMP compliant'],
    logistics: 'FOB Mundra to Ho Chi Minh City (VNSGN): 12–16 days. Hai Phong also served for Northern Vietnam buyers.',
    regulatoryNote: 'Health supplements in Vietnam are regulated by DAV (Drug Administration of Vietnam) under the Ministry of Health. Import registration is required.',
    faqs: [
      { q: 'What documentation is needed for psyllium import into Vietnam?', a: 'We provide full Vietnam import documentation including: COA, phytosanitary certificate, certificate of origin, MSDS, and product technical specifications for DAV import registration.' },
      { q: 'What is the transit time from India to Vietnam?', a: 'FOB Mundra to Ho Chi Minh City takes 12–16 days. Northern Vietnam (Hai Phong) is similar.' },
      { q: 'Can you supply small MOQ for Vietnamese importers?', a: 'Yes. Vietnam market buyers often start with smaller trial orders. We accommodate MOQ from 500 kg for Vietnamese buyers with LCL shipment options.' },
      { q: 'Do you supply to Vietnamese traditional medicine (thuốc đông y) manufacturers?', a: 'Yes. Psyllium husk is used in traditional Vietnamese medicine preparations. We can supply to both Western-style supplement manufacturers and traditional medicine companies.' },
    ],
  },
  {
    slug: 'indonesia',
    name: 'Indonesia',
    flag: '🇮🇩',
    region: 'Asia-Pacific',
    currency: 'IDR',
    buyerSegments: ['BPOM registered manufacturers', 'Halal food companies', 'Jamu herbal brands', 'Health supplement distributors'],
    primaryKeywords: ['Psyllium Husk Supplier Indonesia', 'Bulk Psyllium Indonesia', 'Halal Psyllium Indonesia', 'Isabgol Supplier Indonesia', 'Psyllium Jakarta'],
    marketIntro: 'Indonesia, with a population of 280 million and world\'s largest Muslim population, is one of Asia\'s most important markets for Halal-certified health products. BPOM (National Agency of Drug and Food Control) regulates supplement imports, and psyllium husk is an approved functional food ingredient.',
    importReason: 'Indonesian manufacturers import Halal-certified bulk psyllium husk from India for fiber supplements, functional food products, and Jamu (traditional herbal) formulations. India\'s ability to supply Halal-certified, quality-tested psyllium at competitive prices makes it the preferred source.',
    certifications: ['MUI Halal certified (essential for Indonesia)', 'BPOM compliant documentation', 'ISO 22000', 'HACCP', 'GMP'],
    logistics: 'FOB Mundra to Tanjung Priok (Jakarta): 12–16 days. Surabaya (IDSUB) also served.',
    regulatoryNote: 'All food products in Indonesia must comply with BPOM regulations and carry MUI (Majelis Ulama Indonesia) Halal certification for Muslim consumer market acceptance.',
    faqs: [
      { q: 'Is your psyllium husk MUI Halal certified for Indonesia?', a: 'Our products carry recognized Halal certification. For MUI-specific certification requirements for Indonesian BPOM registration, we provide the necessary supporting documentation and work with our Indonesian buyers through the process.' },
      { q: 'Do you provide BPOM-compatible import documentation?', a: 'Yes. We provide full technical documentation required for BPOM product notification including: COA, specification sheets, manufacturing process, and quality system documentation.' },
      { q: 'What is transit time from India to Indonesia?', a: 'FOB Mundra to Tanjung Priok (Jakarta) takes 12–16 days. One of the shortest India-ASEAN routes.' },
      { q: 'Can you supply psyllium for Indonesian Jamu (traditional herbal) products?', a: 'Yes. Psyllium husk is incorporated in traditional Indonesian herbal formulations. We supply both conventional and organic grades for Jamu manufacturers.' },
    ],
  },
];

/** Helper to find a country by slug */
export function getCountryBySlug(slug: string): CountryData | undefined {
  return COUNTRIES.find(c => c.slug === slug);
}

/** All country slugs for generateStaticParams */
export const COUNTRY_SLUGS = COUNTRIES.map(c => c.slug);
